// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQF3VcS17pdF6mzlDDVr_un2bB2I6wigc',
    appId: '1:330566038499:web:57ccc7ca6fbe49d423a6d6',
    messagingSenderId: '330566038499',
    projectId: 'car-project-abdelmalek',
    authDomain: 'car-project-abdelmalek.firebaseapp.com',
    storageBucket: 'car-project-abdelmalek.firebasestorage.app',
    measurementId: 'G-E34E7KSP7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVloT9LZUm5MPHponSMjbxOSIr2WeV3c',
    appId: '1:330566038499:android:5dbabffc362b72cc23a6d6',
    messagingSenderId: '330566038499',
    projectId: 'car-project-abdelmalek',
    storageBucket: 'car-project-abdelmalek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4R3LRVuuOE2zh-Vv8Fp_hVZl_n806_xo',
    appId: '1:330566038499:ios:acc14e8a1b92ad6c23a6d6',
    messagingSenderId: '330566038499',
    projectId: 'car-project-abdelmalek',
    storageBucket: 'car-project-abdelmalek.firebasestorage.app',
    iosBundleId: 'com.example.carApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4R3LRVuuOE2zh-Vv8Fp_hVZl_n806_xo',
    appId: '1:330566038499:ios:acc14e8a1b92ad6c23a6d6',
    messagingSenderId: '330566038499',
    projectId: 'car-project-abdelmalek',
    storageBucket: 'car-project-abdelmalek.firebasestorage.app',
    iosBundleId: 'com.example.carApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQF3VcS17pdF6mzlDDVr_un2bB2I6wigc',
    appId: '1:330566038499:web:7fd1dd179d33067423a6d6',
    messagingSenderId: '330566038499',
    projectId: 'car-project-abdelmalek',
    authDomain: 'car-project-abdelmalek.firebaseapp.com',
    storageBucket: 'car-project-abdelmalek.firebasestorage.app',
    measurementId: 'G-XHZJD64BWN',
  );
}
